### ISSUE TITLE
Nested \iffalse \fi block comments.

### ISSUE THREAD

**Issue by LorenzoNajt** [google-research/arxiv-latex-cleaner#12]
I used \iffalse ... \fi to block comment in my latex document, and used this modification of the  _remove_environment command:

```
def _remove_iffalse(text):
  """Removes '\\iffalse *\\fi' from 'text'."""
  """This has problems with nested \\iffalse \\fi statements"""
  return re.sub(
      r'\\iffalse[\s\S]*?\\fi',
      '', text)

```
However, this runs incorrectly on:
```
\iffalse
A
\iffalse
B
\fi
C
\fi
```

Which in latex outputs nothing, but with the _remove_iffalse code above outputs:

```
C
\fi
```

(I had one such nested comment in my document, because of commenting out a subsection of a section that was later commented out in its entirety.)

A similar problem does not exist for \begin{comment} \end{comment}, because 

```
\begin{comment}
A
\begin{comment}
B
\end{comment}
C
\end{comment}
```

Does not compile in Latex.

**Comment by jponttuset** [comment]
Hi @LorenzoNajt,
Thanks for reporting this. I marked it as an enhancement.
It would need an iterative run of various regex detecting \iffalse\fi, each of them without any nested \iffalse\fi.
Best,
