### ISSUE TITLE
Propose to add an option for not resizing images and figures

### ISSUE THREAD

**Issue by Ir1d** [google-research/arxiv-latex-cleaner#13]

**Comment by jponttuset** [comment]
Hi @Ir1d,

Thanks for the suggestion, marking it as an enhancement.

Best,

**Comment by jponttuset** [comment]
In the meantime, you can use `--im_size=1000000000` which will effectively not ersize any image (images only get downscaled, not upscaled)

**Comment by jponttuset** [comment]
Hi @Ir1d,

In 6fe243a3bc6c057fc44ef4c0b27d7ee3c3e66954 I just added a parameter called "resize_images", that will leave all images untouched if set to False.
