### ISSUE TITLE
Unneeded files are copied.

### ISSUE THREAD

**Issue by harald-lang** [google-research/arxiv-latex-cleaner#16]
When some input command is commented out (e.g., `% \input{some/file}`) the referenced file is copied to the output directory anyhow.

**Comment by jponttuset** [comment]
Sorry for the delay, I'll fix this soon.

**Comment by jponttuset** [comment]
Fixed in 8de5050cda4b11d45155881d544d82b04eca6941
Please let me know if you still find some issues.
