### ISSUE TITLE
[fueature request] remove the fig unused

### ISSUE THREAD

**Issue by JiahaoYao** [google-research/arxiv-latex-cleaner#17]
I wonder if it is possible to remove the untouched figures in the folder during the cleaning.

**Comment by jponttuset** [comment]
Hi @JiahaoYao,

What do you mean by "untouched figures"? Could you provide a minimal example that doesn't work?

Best,

**Comment by JiahaoYao** [comment]
Hi @jponttuset, my bad. It turns out this feature is already supported. Thank you !
