### ISSUE TITLE
PyPI deployment

### ISSUE THREAD

**Issue by So-Cool** [google-research/arxiv-latex-cleaner#20]
Hi, is there any particular reason why this package is not deployed to PyPI?

**Comment by jponttuset** [comment]
Thanks for the suggestion, no particular reason.
I'll add it to PyPI soon.

**Comment by So-Cool** [comment]
I was actually thinking of getting Travis CI configured and automatising the deployment to PyPI whenever a commit is tagged. This would make code versioning more manageable.

Do you know whether Travis is enabled for the google-research GitHub org? I'm happy to do a PR with all of these enhancements.

**Comment by hayesall** [comment]
I also like the "deploy on tag" suggestion. @So-Cool if Travis CI is not configured, you might also look into setting this up through Actions.

Here's an example action I use to publish to PyPi when a tag is created: [`pythonpublish.yml`](https://github.com/hayesall/srlearn/blob/88c1c0fbd6f2fa037c0ab152988518dfaa190c56/.github/workflows/pythonpublish.yml). It requires setting repository secrets, which @jponttuset should be able to define in the repository settings.

**Comment by So-Cool** [comment]
It very much depends on whether there's any benefit from running the unit tests automatically. What do you think @jponttuset? It seems that Travis is configured for the google-research org since it is used with other repositories here.

**Comment by jponttuset** [comment]
Hi @So-Cool and @hayesall! Thanks for your initiative!

I have no experience with Travis CI or Actions (nor PyPI for that matter :p), but given the low number of changes that we submit, I wouldn't mind running tests and updating PyPI manually every time there is a change.

Having said that, I'm also open to accept your PR setting it up.

> Do you know whether Travis is enabled for the google-research GitHub org?
I can ask if necessary.

> It requires setting repository secrets, which @jponttuset should be able to define in the repository settings.
I can do that if needed.

I'll start setting up the PyPI end.

Thanks again!

**Comment by So-Cool** [comment]
It seems best to proceed with GitHub Actions. I'll prepare a PR and we can take it from there.

**Comment by jponttuset** [comment]
I just added arxiv-latex-cleaner to PyPi:
https://pypi.org/project/arxiv-latex-cleaner/

Although for me manually updating PyPi is fine, feel free to set "GitHub Actions" up. I'll close this issue but feel free to ping me if you need help.
