### ISSUE TITLE
Image reference check wrongly admits prefix of referenced image

### ISSUE THREAD

**Issue by aditya95sriram** [google-research/arxiv-latex-cleaner#22]
Let's say I have two images called `include_image_yes.png` and `include_image.png`, and I only reference `include_image_yes.png` while `include_image.png` is not referenced anywhere. The tool thinks of `include_image.png` as being referenced just because it appears as a prefix of `include_image_yes.png` (extensions are ignored for this check, which is unavoidable). This happens even when the images are not in root and inside some directory like `images`. 

I've tracked it down to the `_keep_only_referenced` function ([link](https://github.com/google-research/arxiv-latex-cleaner/blob/f1897b3addc83d5ab8906dbab35be1618b46a9ea/arxiv_latex_cleaner/arxiv_latex_cleaner.py#L234)) and so it's possible that this affects more than just images. A possible fix could be to use a slightly more elaborate regex check which searches for `include_image\b`, with a word boundary metacharacter to prevent such false positives.

**Comment by jponttuset** [comment]
Hi @aditya95sriram 

Thanks for reporting this. I was aware of the issue, I marked it as bug.
If you have the time, I'd really appreciate if you could do a PR. :)

Best,

**Comment by aditya95sriram** [comment]
Ok, I can give it a go.

Do you think it's better to add word boundaries to both the start and the end, e.g. the search for references of file `include_image.png` would correspond to the regex search `\binclude_image\b`. I presume this would help resolve the following case as well but I'm not sure if that would break something else.

```
...
├── images
│   ├── im1_included.png
│   ├── im2_included.jpg
│   ├── im3_included.png  (not referenced)
│   ├── im_not_included.png
│   └── include
│       └── images
│           └── im3_included.png  (referenced)
...
```

In the above example, the `images/im3_included.png` is marked as referenced because it appears as a substring in `images/include/images/im3_included.png`

**Comment by jponttuset** [comment]
I don't think we can resolve this case because of the `\graphicspath` functionality that allows you to include graphics with relative paths. You would have no way to know which `im3_included.png` is the one included... 
But now that I think of it, I actually don't know if the current implementation supports relative paths or it assumes all paths are absolute...

In any case:
- At the end of the word, can we assume that it must be either `}` (with spaces before, maybe?) or one of the valid figure extensions? I cannot come up with any other possible case.
- At the beginning of the word, isn't it either `{` (with spaces after, maybe?) or `os.path.sep`?

If you want to give it a try, run the integration tests and if they pass, I'd go ahead :)

**Comment by aditya95sriram** [comment]
I was also wondering about `\graphicspath`. But for now, the assumptions you state seem to be reasonable. Keeping those in mind, we'd get the following regex 
```regex
\{[\s%]*<basename>(.jpg|.png|.jpeg|.pdf)?[\s%]*\}
```
where `basename` is the filename without the extension (possibly also including path to the file)

The percent (`%`) is there to handle cases like

```tex
\includegraphics{%
path/to/file%
}
```

Also, it might be better to not hardcode `.jpg|.jpeg|.png|.pdf` and rather use `parameters['figures_to_copy_if_referenced']` for future-proofing.

**Comment by jponttuset** [comment]
Looks good!
Yeah, let's use `parameters['figures_to_copy_if_referenced']`.
Could you create a PR? If so, please add some test cases that cover these new cases (percent).
Thanks!

**Comment by aditya95sriram** [comment]
Yes, I'm in the process of creating a PR. Had some more minor queries before finalizing it. Apparently the function `_keep_only_referenced` is also invoked by `_copy_only_referenced_non_tex_not_in_root` for which I think the extensions part behaves differently.

Am I correct to assume that for non-tex non-image files the extension must always be included when referencing it?
e.g. is it ever valid to refer to the file `data_included.txt` as `data_included` ?

**Comment by aditya95sriram** [comment]
This also brings up another related point, where the regex extension part should not check for all extensions but just the specific extension of that file.

For instance, if you have two files `im1_included.png` and `im1_included.jpg` but only one of them is referenced as `\includegraphics{im1_included.png}`, both of them would be flagged as being referenced. If we just check for the particular extension, i.e. for `im1_included.png` we use the regex `im1_included(.png)?` then this issue does not arise.
