### ISSUE TITLE
New encoding error as a result of fixing previous one.

### ISSUE THREAD

**Issue by pzpzpzp1** [google-research/arxiv-latex-cleaner#27]
I used pip to install and when trying to use the cleaner ran into a new encoding error. 
Googling around suggested that it's because some versions of python don't support the added encoding utf8 change.
It was fixed by adding "from io import open" to the top of the arxiv-latex-cleaner.py file.

**Comment by jponttuset** [comment]
Thanks @pzpzpzp1,

FYI, I guess you're using Python 2, which lost support in [January 1, 2020](https://www.python.org/doc/sunset-python-2/).
I'll explore whether I add this fix or I just mark the package as Python 3 only, as I'm not sure if adding this package might have some performance issues down the road.

Best,

**Comment by hayesall** [comment]
This might also be resolved with more clear installation instructions:

`pip` usually points to the `python2` packages, while `pip3` affects the `python3` packages by default.

@pzpzpzp1 would clarifying with the following snippet resolve this issue?

```bash
pip3 install arxiv-latex-cleaner
```

**Comment by jponttuset** [comment]
Marked the package as Python >=3 only in https://github.com/google-research/arxiv-latex-cleaner/commit/ccbdb1194562e626fff4d04f74782d7c76254aba
