### ISSUE TITLE
bib file gets removed 

### ISSUE THREAD

**Issue by peymmo** [google-research/arxiv-latex-cleaner#28]
The .bib files removed after cleaning in linux.

**Comment by jponttuset** [comment]
Hi @peymmo,
This is the expected behavior, as arXiv expects only the .bbl file to be submitted, not the .bib.
Best,

**Comment by MaStFAU** [comment]
i am having the same "issue". would be nice to have a flag to set this as optional as it is great tool for many other use cases as well!

**Comment by jponttuset** [comment]
I'd be OK with adding a flag to keep the `.bib` file, being `false` by default.
PRs are welcome.
