### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Vaufreyd** [google-research/arxiv-latex-cleaner#4]
Dear authors,

Thank you very much for the arxiv cleaner (I was starting to write my own one when I discover by chance that you already did).

You current version is not working on Windows as python will use '\\' as separator (os.sep value) and this breaks regular expressions. I did a version that works also on Windows (replacing os.path.join to make it behave like in Linux). Should I share the code and ask for a pull request?

Best regards. Doms.

**Comment by jponttuset** [comment]
Dear Doms,
Glad you found our code useful, and sorry that it did not work out of the box for you.
Pull requests are more than welcome! Thanks!
Best,

**Comment by jponttuset** [comment]
Thanks Doms, merged you PR, thanks again!
(Fixed in #5)
