### ISSUE TITLE
commented \end{document} is processed

### ISSUE THREAD

**Issue by AdrienCorenflos** [google-research/arxiv-latex-cleaner#45]
Hi,

Thanks for putting this out there, it's pretty neat and useful tool!

It seems that you rely on parsing \end{document} to truncate the .tex file? If this \end{document} is commented, this still truncates the whole file afterwards. Maybe you should run this stripping after all comments have been removed so as to not delete content inadvertently?

Adrien

**Comment by jponttuset** [comment]
Thanks for reporting this!
I'm marking it as bug for the moment, until I have time to solve it or someone might consider sending a PR :)

**Comment by shilpeePrasad** [comment]
Hi, I would like to work on this issue. Could you please explain the issue in more detail with example. Thanks

**Comment by AdrienCorenflos** [comment]
Hi

Just try it for this example:

```latex
\documentclass{article}

\begin{document}
Some text
%\end{document}
\end{document}
```

**Comment by AdrienCorenflos** [comment]
> Hi
> 
> Just try it for this example:
> 
> ```
> \documentclass{article}
> 
> \begin{document}
> Some text
> %\end{document}
> \end{document}
> ```

Actually, looks like there isn't enough in this for it to be picked up by the cleaner. Will revert with a minimal example later.
