### ISSUE TITLE
Commands_to_delete ignores commands with options

### ISSUE THREAD

**Issue by MarcinNaw** [google-research/arxiv-latex-cleaner#48]
It seems that commands with preceding  options are not filtered, e.g.:

```
arxiv_latex_cleaner "${dir}" --commands_to_delete "todo"
```
This will *not* drop the following command:

```
\todo[inline]{valve pls fix}
```

Did I use the wrong command?

PS: Thank you for this great tool.

**Comment by jponttuset** [comment]
You're right, we did not consider this case. Marking as bug.

**Comment by Waterkin** [comment]
Also for sth like:`\begin{table*}[!t]`

**Comment by dylduhamel** [comment]
It looks like this bug still exists on the main branch. I believe it is due to regex not matching some edge cases as described above. I am happy to work on it.

**Comment by ndvbd** [comment]
Still doesnt work for me
