### ISSUE TITLE
Is it possible to update `absl-py>=0.12`?

### ISSUE THREAD

**Issue by felixfrank** [google-research/arxiv-latex-cleaner#53]
Old `absl-py` versions do not work with python 3.10 because they incorrectly do a string comparison on the python version, see this [issue](https://github.com/abseil/abseil-py/issues/161). This was fixed with v0.12. Is there a particular reason to require `absl-py~=0.6.1`?

**Comment by jponttuset** [comment]
Thanks @felixfrank, upgraded the requirements file.
