### ISSUE TITLE
does not copy PDF images that contain "()" in file name

### ISSUE THREAD

**Issue by phguo** [google-research/arxiv-latex-cleaner#79]
I have figures like `/manuscript/(a).pdf`. They are not copied when I run arxiv-latex-cleaner by `arxiv_latex_cleaner manuscript --keep_bib --commands_to_delete cmt todo sout --verbose`.

**Comment by jponttuset** [comment]
In principle, this is now fixed thanks to #84.
Please @phguo reopen in case you're still seeing the issue.
