### ISSUE TITLE
How to delete extra blank lines?

### ISSUE THREAD

**Issue by lartpang** [google-research/arxiv-latex-cleaner#81]
This is a very useful tool. But after removing the annotation content, there will be many duplicate blank lines left. How should I delete it?

**Comment by jponttuset** [comment]
Hi @lartpang 
The duplicated blank lines do not affect the generated output, so we chose to leave them there, since trying to remove them might cause more problems. If you really need to erase the duplicated blank lines, it should be quite straightforward to do with a regex expression.
