### ISSUE TITLE
[BUG] Inline comment containing a url is not removed

### ISSUE THREAD

**Issue by merajhashemi** [google-research/arxiv-latex-cleaner#91]
Hi 👋 
When there is an inline comment followed by a \url{} command, the inline comment is not removed as expected. This issue seems to have been introduced while addressing #82.

### Input:
```latex
Hello! % (\url{topsecret.com})
```
### Output:
```latex
Hello! %
\url{topsecret.com})
```
### Expected Output:
```latex
Hello! %
```

**Comment by jponttuset** [comment]
Thanks @merajhashemi!
