### ISSUE TITLE
[Unexpected Behavior] Comments Not Removed on Lines with "auto-ignore"

### ISSUE THREAD

**Issue by merajhashemi** [google-research/arxiv-latex-cleaner#93]
While fixing issue #91, I discovered that comments in lines containing the word `auto-ignore` are not being removed as expected. This behavior is not documented in either the README or the help message, which may lead to unexpected outcomes for users. 
I suppose there is a specific reason for this behavior as it is also being tested 🤔

### Input:
```latex
Foo auto-ignore Bar ... % Top Secret Comment
```
### Output:
```latex
Foo auto-ignore Bar ... % Top Secret Comment
```
### Expected Output:
```latex
Foo auto-ignore Bar ... %
```

**Comment by jponttuset** [comment]
Hi @merajhashemi!
The rationale for this behavior is that arXiv uses this %auto-ignore comment to mark a file as not being the main tex file to be compiled. You can see more info [here](https://info.arxiv.org/help/faq/mistakes.html). We could definitely make the content matching more strict (e.g. there cannot be more text apart from "auto-ignore"), feel free to send a PR if you're up for it :)

**Comment by merajhashemi** [comment]
Hi @jponttuset!
Thanks for letting me know about this! I didn't realize arXiv uses the `%auto-ignore` comment in that way. I've opened a pull request (#96) to tighten the content matching.

**Comment by jponttuset** [comment]
I made a small suggestion in the PR not to over-tighten the matching :)
